# Generated by Django 2.2 on 2021-02-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='email',
            new_name='Budget',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='name',
            new_name='Preference',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='phone',
            new_name='Time_Frame',
        ),
    ]
