# Generated by Django 2.2 on 2021-02-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0002_auto_20210211_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={},
        ),
        migrations.RemoveField(
            model_name='selection',
            name='publish',
        ),
    ]
