# Generated by Django 2.2 on 2021-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0003_auto_20210212_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='Budget',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selection',
            name='Time_Frame',
            field=models.IntegerField(max_length=50),
        ),
    ]
