# Generated by Django 2.2 on 2021-02-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0004_auto_20210212_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='Budget',
            new_name='Budget_Dollar',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='Time_Frame',
            new_name='Time_Frame_Hour',
        ),
    ]
