# Generated by Django 2.2 on 2021-02-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recreation_Type_Indoor', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Recreation_Type_Outdoor', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Public', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Private', models.CharField(blank=True, default=' ', max_length=50, null=True)),
            ],
        ),
    ]
