# Generated by Django 2.2 on 2021-02-11 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='type',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='type',
            name='Private',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='Public',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='Recreation_Type_Indoor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='Recreation_Type_Outdoor',
            field=models.CharField(max_length=50),
        ),
    ]
