# Generated by Django 2.2 on 2021-02-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Type', '0002_auto_20210211_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.RemoveField(
            model_name='type',
            name='publish',
        ),
    ]
