# Generated by Django 2.2 on 2021-02-11 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='people',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
